### PR TITLE
Merging MediaWiki codebase

### PR DESCRIPTION
**Pull request by samwilson**
This merges the WeRelate codebase into MediaWiki version 1.7.1 (with all history from both sides).

The added files are listed below. These are just the files that are in 1.7.1 but not present in WeRelate; I don't think there's anything there that will cause any trouble.

The idea is that after this PR is merged, it'll be easy to not only see what's changed (e.g. `git diff 5f4988e --diff-filter=M`will show all WeRelate modifications to core) but also make it easier to progressively merge newer MediaWiki versions, and bring the codebase up-to-date.

```
AdminSettings.sample
INSTALL
README
config/index.php
docs/README
docs/database.txt
docs/deferred.txt
docs/design.txt
docs/export-0.1.xsd
docs/export-0.2.xsd
docs/export-0.3.xsd
docs/export-demo.xml
docs/globals.txt
docs/hooks.txt
docs/html/README
docs/language.txt
docs/linkcache.txt
docs/magicword.txt
docs/memcached.txt
docs/php-memcached/ChangeLog
docs/php-memcached/Documentation
docs/schema.txt
docs/skin.txt
docs/title.txt
docs/user.txt
extensions/README
images/README
locale/README
profileinfo.php
redirect.phtml
skins/Chick.deps.php
skins/Chick.php
skins/CologneBlue.php
skins/MySkin.deps.php
skins/MySkin.php
skins/Nostalgia.php
skins/Simple.deps.php
skins/Simple.php
skins/Skin.sample
skins/SkinPHPTal.sample
skins/Standard.php
skins/chick/IE50Fixes.css
skins/chick/IE55Fixes.css
skins/chick/IE60Fixes.css
skins/chick/main.css
skins/common/images/mediawiki-large.xcf
skins/common/images/mediawiki-largesquare.xcf
skins/disabled/HTMLDump.php
skins/disabled/MonoBook.tpl
skins/disabled/MonoBookCBT.php
skins/htmldump/lookup.js
skins/htmldump/main.css
skins/htmldump/md5.js
skins/htmldump/utf8.js
skins/myskin/main.css
skins/simple/discussionitem_icon.gif
skins/simple/external.png
skins/simple/file_icon.gif
skins/simple/link_icon.gif
skins/simple/lock_icon.gif
skins/simple/mail_icon.gif
skins/simple/main.css
wiki.phtml
```

### CODE REVIEW

**Comment by samwilson** [comment]
Hi @DallanQ I've been having another look at what it might take to update WeRelate to modern Mediawiki. I still think merging history is a good way to go, to make it easy at each upgrade step to see what's different and what needs investigation.

Is this something you're still keen on?

I don't have a huge amount of time, but am working full-time on MediaWiki these days so it's less of a context switch to do this stuff after hours. :-) There's some discussion on the Wikimedia genealogy mailing list about what the best wiki-based genealogy solution could be, and of course WeRelate is the primary project.

**Comment by DallanQ** [comment]
Yes! If you're interested In doing the work I will support it. How would you like to proceed? I know this thread is old; can we start simply by merging this PR?

**Comment by samwilson** [comment]
Yeah, I think you should be able to merge this without dramas. Just check the file list about to see if you can see any PHP files that might cause problems.

**Comment by DallanQ** [comment]
closing old PRs

**Pull request closed without merging**
